# Common Network Security Threats: A Research Report

## Introduction

Modern organizations run almost every core function on shared, interconnected networks: payments, communications, healthcare records, industrial control, critical infrastructure. That dependence makes the network layer one of the most attractive attack surfaces in cybersecurity today. A single successful network attack can take a hospital's systems offline, drain a bank account, redirect millions of users to a malicious site, or cascade into a multi-day outage for services the internet as a whole relies on. Attack tooling has also gotten cheaper and more automated: botnets are available for rent, exploit code leaks and gets reused, and AI-assisted reconnaissance lowers the skill bar further, so even unsophisticated actors can now pull off attacks that used to require nation-state resources. Knowing how these threats actually work, rather than just that they exist, is what lets network administrators prioritize defenses, design resilient architectures, and respond effectively when prevention fails. Four threats are covered below: Denial-of-Service/Distributed Denial-of-Service (DoS/DDoS) attacks, Man-in-the-Middle (MITM) attacks, IP spoofing, and DNS poisoning/spoofing, each with its mechanics, a documented real-world incident, and concrete mitigation strategies.

---

## 1. Denial-of-Service (DoS) and Distributed Denial-of-Service (DDoS) Attacks

### How It Works
A DoS attack overwhelms a target system, service, or network link so that legitimate users cannot access it — NIST defines denial of service as the prevention of authorized access to a resource or the delaying of time-critical operations. A DDoS attack is a DoS technique that uses **numerous distributed hosts** (often a botnet of compromised devices) to perform the attack simultaneously, making it far harder to block by filtering a single source. CISA, FBI, and MS-ISAC jointly categorize DDoS techniques into three types: **volumetric** attacks that consume available bandwidth, **protocol** attacks that exploit weaknesses in network protocols (e.g., SYN floods), and **application-layer** attacks that target vulnerabilities in specific applications or services (e.g., HTTP floods).

### Real-World Example
On **September 20, 2016**, journalist Brian Krebs' security blog, KrebsOnSecurity.com, was hit by a DDoS attack exceeding 620 Gbps — one of the largest ever recorded at the time — generated by the **Mirai botnet**, malware that scans the internet for IoT devices (routers, DVRs, IP cameras) still using default factory credentials and enlists them as attack nodes. A month later, on October 21, 2016, the same Mirai botnet was turned against **Dyn**, a major DNS provider, generating roughly 1.2 terabits of malicious traffic and knocking Dyn offline for hours. Because Dyn resolved DNS for major platforms, the attack cascaded into outages for Twitter, Netflix, PayPal, Reddit, Amazon, and GitHub, illustrating how a DDoS attack on a single piece of shared infrastructure can disrupt a large swath of the internet at once.

### Impact
- Extended service outages leading to direct revenue loss and SLA breaches
- Reputational damage and loss of customer trust
- Operational costs of emergency mitigation and post-incident hardening
- Collateral damage to unrelated services that depend on the same shared infrastructure (as seen in the Dyn incident)

### Mitigation Strategies
1. **Traffic scrubbing / DDoS protection services**: Route traffic through a CDN or dedicated DDoS mitigation provider (e.g., cloud-based scrubbing centers) that can absorb and filter volumetric traffic before it reaches origin servers, as CISA's Capacity Enhancement Guide recommends for evaluating CDN, ISP, and cloud-hosted mitigation options.
2. **Rate limiting and traffic filtering**: Apply rate limits on connections/requests per source, and use firewalls or upstream ISP filtering to drop malformed or excessive traffic, particularly protocol-layer abuse such as SYN floods.
3. **Network redundancy and capacity planning**: Maintain redundant bandwidth, geographically distributed infrastructure, and a documented incident response/communication plan so that a volumetric spike against one node or region does not take the whole service down, coupled with active partnerships with upstream providers who can implement blocks quickly.

---

## 2. Man-in-the-Middle (MITM) Attacks

### How It Works
In a MITM (also called Adversary-in-the-Middle, or AiTM, per MITRE ATT&CK technique **T1557**) attack, an adversary secretly positions itself between two communicating parties to eavesdrop on, intercept, or alter traffic — typically without either party realizing the channel has been compromised. Attackers achieve this position by abusing weaknesses in protocols that determine traffic flow, such as ARP cache poisoning, rogue/"evil twin" Wi-Fi access points, DNS manipulation, or SSL/TLS downgrade attacks that force a connection to use a weaker or forged certificate. Once positioned, the attacker can passively collect credentials and session tokens, or actively modify data in transit.

### Real-World Example
Starting in **2014**, Lenovo shipped consumer laptops preloaded with "Superfish" adware that installed a self-signed root certificate on every device — using the **same private key across all affected machines**. This let Superfish (and anyone who extracted that key) transparently intercept and re-sign HTTPS traffic to inject ads, meaning any attacker on the same network as a Superfish-equipped laptop could forge valid-looking certificates for banking or email sites and intercept supposedly encrypted traffic. Separately, in 2017 the **Equifax** mobile applications were pulled from app stores after researchers found the apps did not consistently enforce HTTPS, leaving user sessions exposed to interception on untrusted networks during the same period Equifax was managing the fallout of its massive data breach.

### Impact
- Theft of credentials, session tokens, and financial/personal data in transit
- Undermining of the trust model that HTTPS/TLS is designed to guarantee
- Regulatory and legal exposure (e.g., lawsuits and multimillion-dollar settlements tied to the Superfish incident)
- Follow-on attacks such as credential replay, account takeover, or lateral movement into corporate networks

### Mitigation Strategies
1. **Enforce end-to-end encryption with strict certificate validation**: Use HTTPS/TLS everywhere, enable HSTS, and use certificate pinning for high-value applications so that forged or improperly issued certificates are rejected rather than silently trusted.
2. **Harden network-layer protocols against spoofing**: Deploy dynamic ARP inspection, DHCP snooping, and switch port security to prevent ARP/DHCP-based positioning attacks on local networks, per the protections MITRE ATT&CK documents against T1557 sub-techniques.
3. **Avoid untrusted networks and use a trusted VPN**: Discourage use of unauthenticated public Wi-Fi for sensitive transactions, and require a corporate VPN with mutual authentication so traffic is encrypted end-to-end regardless of the underlying network's trustworthiness.

---

## 3. IP Spoofing

### How It Works
IP spoofing is the practice of crafting network packets with a **forged source IP address** so that the packet appears to originate from a different, often trusted or victim, host. Because IP is inherently connectionless and does not authenticate the source address, spoofing is straightforward for any protocol that does not require a completed handshake, most notably UDP. Attackers commonly exploit this for **reflection/amplification DDoS attacks**: they send a small request to a third-party server, spoofing the victim's IP address as the source, so the server's (often much larger) response is sent to the victim instead of the attacker — amplifying the attacker's effort while hiding their identity.

### Real-World Example
On **February 28, 2018**, GitHub was hit by a **1.35 Tbps** DDoS attack — at the time the largest ever recorded — using spoofed-IP requests against publicly exposed **memcached** servers. Attackers stored large payloads on misconfigured memcached servers (reachable over UDP with no authentication) and then sent tiny "get" requests with GitHub's IP address spoofed as the source; each server responded with a payload up to ~51,000 times larger than the request, all directed at GitHub. GitHub was unavailable or intermittently degraded for roughly 8–10 minutes before Akamai Prolexic absorbed and filtered the traffic. Cloudflare, which had disclosed the memcached amplification vector days earlier, explicitly called on ISPs to implement **anti-spoofing filtering** (BCP 38) to prevent forged-source packets from ever leaving a network in the first place.

### Impact
- Amplification-based DDoS attacks capable of overwhelming even large, well-resourced targets
- Evasion of IP-based access controls and trust relationships (e.g., spoofing a trusted internal IP to bypass firewall rules)
- Difficulty attributing attacks to their true origin, hampering incident response and law enforcement
- Exposure of misconfigured third-party infrastructure (like open memcached servers) as unwitting attack amplifiers

### Mitigation Strategies
1. **Ingress/egress filtering (BCP 38 / RFC 2827)**: ISPs and network operators should filter traffic to ensure a packet's source address is legitimately within the range of the network it enters or exits from, which prevents spoofed packets from propagating.
2. **Disable or restrict unauthenticated UDP services**: Turn off UDP support on services like memcached that do not need it, restrict them to internal networks/firewalled access, and rate-limit or block traffic on known amplification-abused ports.
3. **Deploy anti-spoofing and monitoring controls at the network edge**: Use router/firewall features such as Unicast Reverse Path Forwarding (uRPF) to reject packets whose source address doesn't match the expected inbound interface, combined with traffic anomaly monitoring to detect reflection attacks early.

---

## 4. DNS Poisoning / DNS Spoofing (Bonus Threat)

### How It Works
DNS poisoning (cache poisoning) corrupts the records stored by a DNS resolver so that queries for a legitimate domain return an attacker-controlled IP address instead of the real one. Historically, the most consequential technique was the **Kaminsky attack**, disclosed in 2008, which exploited the fact that DNS responses were authenticated only by a 16-bit transaction ID (roughly 65,536 possible values) and a fixed source port. An off-path attacker could flood a resolver with forged responses for random subdomains while racing the real authoritative server's reply; because the attacker could guess the transaction ID often enough with enough attempts, forged records would eventually be cached — including the ability to hijack an entire domain's "authority" records rather than just a single hostname. Once poisoned, every subsequent user of that resolver could be silently redirected to a malicious server.

### Real-World Example
In **March 2010**, a Swedish ISP outside China accidentally configured its DNS servers to pull records from Chinese DNS servers that were enforcing the Great Firewall's censorship of sites like Twitter, Facebook, and YouTube; the poisoned records propagated and cached globally, making some of these sites briefly inaccessible even to users in the United States whose resolvers had cached the bad data. This incident showed how DNS poisoning — whether malicious or accidental — can spread far beyond its original target because of how resolvers cache and share records. Separately, the 2008 disclosure of the Kaminsky bug itself was treated as a near-internet-wide emergency, prompting a coordinated, multi-vendor patch release because so many DNS resolvers worldwide shared the same underlying weakness.

### Impact
- Silent redirection of users to phishing or malware-hosting sites while the address bar shows a trusted domain
- Interception of credentials, session cookies, and sensitive form data submitted to spoofed sites
- Erosion of trust in DNS as a naming authority, with effects that can persist due to caching (TTL) even after the underlying vulnerability is fixed
- Potential for censorship or large-scale redirection when poisoning affects upstream/recursive resolvers used by many downstream networks

### Mitigation Strategies
1. **Deploy DNSSEC**: Domain Name System Security Extensions cryptographically sign DNS records so resolvers can verify a response's authenticity and reject forged data, directly closing the trust gap that made the Kaminsky attack possible.
2. **Randomize transaction IDs and source ports**: Ensure DNS resolver software uses fully randomized query IDs and source ports (the fix rolled out industry-wide after 2008) to make blind response-forging attacks computationally infeasible.
3. **Use encrypted DNS and restrict/monitor resolver caching behavior**: Adopt DNS over HTTPS (DoH) or DNS over TLS (DoT) to prevent on-path tampering, enforce conservative TTLs and query-name minimization, and monitor for anomalous record changes on authoritative and recursive resolvers.

---

## Comparison Table

| Threat | Attack Vector | Who Is at Risk | Difficulty to Execute | Ease of Mitigation |
|---|---|---|---|---|
| **DoS/DDoS** | Flooding a target with traffic/requests via a single source or a distributed botnet | Any internet-facing service, especially high-profile or under-resourced targets | Low–Medium (botnets and "booter" services are cheap to rent) | Medium — requires scrubbing services, redundancy, and ongoing capacity planning |
| **Man-in-the-Middle** | Positioning between two parties via ARP poisoning, rogue Wi-Fi, or TLS downgrade | Users on untrusted/public networks; organizations with weak certificate validation | Medium (requires network positioning, e.g., same LAN or rogue AP) | Medium — strong TLS/HSTS and network hardening substantially reduce risk |
| **IP Spoofing** | Forging the source IP address in packets, often for reflection/amplification | Any UDP-based public service; ultimately, any DDoS target reached via amplification | Low (trivial for UDP-based protocols with no source validation) | Medium–High — depends on widespread ISP adoption of ingress filtering (BCP 38) |
| **DNS Poisoning/Spoofing** | Injecting forged DNS responses into a resolver's cache | Any user relying on an unpatched/unsigned DNS resolver; entire downstream networks sharing that resolver | Medium–High (modern resolvers with randomized IDs are far harder to poison than in 2008) | Medium — DNSSEC and encrypted DNS exist but are not universally deployed |

---

## Conclusion: Key Takeaways for Network Administrators

1. **Defense in depth beats any single control.** Every threat in this report — DDoS, MITM, IP spoofing, and DNS poisoning — is far easier to prevent (or contain) when multiple layered controls are in place (e.g., ingress filtering *and* rate limiting *and* redundant capacity for DDoS) rather than relying on one safeguard.
2. **Foundational protocol weaknesses (IP, DNS, ARP) are still exploited at massive scale.** The Mirai/Dyn attack, the GitHub memcached attack, and the Kaminsky DNS bug all trace back to decades-old design assumptions (no source authentication in IP, weak entropy in DNS transaction IDs) — administrators should prioritize protocol-level hardening (uRPF, DNSSEC, randomized ports) alongside application-level defenses.
3. **Shared and third-party infrastructure is a force multiplier for risk.** Misconfigured memcached servers, IoT devices with default credentials, and a single DNS provider (Dyn) each became the vector for attacks with consequences far beyond their own operators — administrators must audit not just their own systems but also the exposure created by upstream providers, IoT devices, and misconfigured shared services on their networks.

---

## References

1. Cybersecurity and Infrastructure Security Agency (CISA), FBI, and MS-ISAC. *Understanding and Responding to Distributed Denial-of-Service Attacks.* CISA.gov. https://www.cisa.gov/resources-tools/resources/understanding-and-responding-distributed-denial-service-attacks
2. National Institute of Standards and Technology (NIST). *Denial of Service — Glossary.* NIST Computer Security Resource Center (CSRC). https://csrc.nist.gov/glossary/term/denial_of_service
3. MITRE ATT&CK®. *Adversary-in-the-Middle, Technique T1557.* MITRE Corporation. https://attack.mitre.org/techniques/T1557/
4. GitHub Engineering. *February 28th DDoS Incident Report.* The GitHub Blog, March 1, 2018. https://github.blog/news-insights/company-news/ddos-incident-report/
5. CISA. *Heightened DDoS Threat Posed by Mirai and Other Botnets.* CISA Alert, 2016. https://www.cisa.gov/news-events/alerts/2016/10/14/heightened-ddos-threat-posed-mirai-and-other-botnets
6. Krebs, B. *Akamai on the Record KrebsOnSecurity Attack.* Krebs on Security, 2016. https://krebsonsecurity.com/2016/11/akamai-on-the-record-krebsonsecurity-attack/
7. unixwiz.net. *An Illustrated Guide to the Kaminsky DNS Vulnerability.* 2008. http://unixwiz.net/techtips/iguide-kaminsky-dns-vuln.html
8. SANS Institute Reading Room. *Information Security Reading Room — Network Security topics.* SANS.org. https://www.sans.org/reading-room/
